### ISSUE TITLE
Refactor internal code

### ISSUE THREAD

**Issue by uki00a** [uki00a/carol#20]

**Comment by Regan-Koopmans** [comment]
Hi @uki00a, is there anything I can do to assist this? Do you have any broad plans for refactoring?

**Comment by uki00a** [comment]
Hi, @Regan-Koopmans, thanks for your comments!

> Do you have any broad plans for refactoring?

I plan to do the following things:

- (**high priority**) `chrome.ts` is messy. I'd like to split this file into separate files (`chrome.ts`, `request.ts`, `errors.ts`, `messages.ts`, etc.)
- (low priority) simplify `chrome.ts` using [puppeteer](https://github.com/puppeteer/puppeteer)
  - [calro](https://github.com/GoogleChromeLabs/carlo), on which this module is based, uses [puppeteer](https://github.com/puppeteer/puppeteer) to provide more flexibility to users.
